/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#a9898a",
        "on-tertiary": "#003921",
        "tertiary-container": "#25a46d",
        "on-primary-fixed": "#40000e",
        "surface-tint": "#ffb2b7",
        "secondary-container": "#45445e",
        "background": "#0D0D1A",
        "secondary-fixed-dim": "#c5c3e2",
        "on-background": "#f7dcdd",
        "outline-variant": "#5a4042",
        "primary-fixed": "#ffdadb",
        "on-primary-fixed-variant": "#91002b",
        "on-error": "#690005",
        "surface-container": "#12121F",
        "surface-variant": "#413031",
        "on-secondary-fixed-variant": "#45445e",
        "surface-container-lowest": "#170b0c",
        "tertiary-fixed-dim": "#67dc9f",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#b71d3f",
        "surface-container-highest": "#413031",
        "inverse-on-surface": "#3d2c2d",
        "error": "#ffb4ab",
        "on-secondary": "#2e2e46",
        "on-primary-container": "#5b0017",
        "primary-container": "#fc536d",
        "secondary-fixed": "#e2dfff",
        "on-primary": "#67001c",
        "surface": "#1d1011",
        "on-tertiary-fixed": "#002111",
        "secondary": "#c5c3e2",
        "inverse-surface": "#f7dcdd",
        "error-container": "#93000a",
        "on-surface": "#f7dcdd",
        "on-tertiary-fixed-variant": "#005232",
        "surface-bright": "#463536",
        "on-tertiary-container": "#00311c",
        "on-surface-variant": "#e2bebf",
        "tertiary": "#67dc9f",
        "on-secondary-fixed": "#191930",
        "tertiary-fixed": "#84f9ba",
        "surface-container-low": "#261819",
        "primary": "#E94560",
        "on-secondary-container": "#b4b2d0",
        "surface-container-high": "#362627",
        "surface-dim": "#1d1011",
        "primary-fixed-dim": "#ffb2b7"
      },
      fontFamily: {
        "kpi": ["Space Mono", "monospace"],
        "label": ["Space Mono", "monospace"],
        "body": ["Inter", "sans-serif"],
        "headline": ["Space Grotesk", "sans-serif"]
      },
    },
  },
  plugins: [],
}
